### ISSUE TITLE
Cannot build go-ipfs v0.4.12 binary

### ISSUE THREAD

**Issue by kevina** [ipfs/distributions#161]
```
Building version v0.4.12 binaries
==> checking out version v0.4.12 in /aux/data-fast/ipfs-distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs
HEAD is now at 8eb7956 Merge pull request #4377 from ipfs/release-0.4.12
HEAD is now at 8eb7956... Merge pull request #4377 from ipfs/release-0.4.12
install deps:%!(EXTRA *errors.errorString=failed to fetch dependencies)
make[2]: *** [gx-deps] Error 1
module.js:471
    throw err;

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/jq/bin/jq:7:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
module.js:471
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/jq/bin/jq:7:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
module.js:471
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/jq/bin/jq:7:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
module.js:471
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/jq/bin/jq:7:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
module.js:471
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/jq/bin/jq:7:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
==> building for darwin 386
    output to ../../releases/go-ipfs/v0.4.12/go-ipfs_v0.4.12_darwin-386
    failed. logfile at '../../releases/go-ipfs/v0.4.12/build-log-darwin-386'
==> building for darwin amd64
    output to ../../releases/go-ipfs/v0.4.12/go-ipfs_v0.4.12_darwin-amd64
    failed. logfile at '../../releases/go-ipfs/v0.4.12/build-log-darwin-amd64'
==> building for freebsd 386
    output to ../../releases/go-ipfs/v0.4.12/go-ipfs_v0.4.12_freebsd-386
    failed. logfile at '../../releases/go-ipfs/v0.4.12/build-log-freebsd-386'
==> building for freebsd amd64
    output to ../../releases/go-ipfs/v0.4.12/go-ipfs_v0.4.12_freebsd-amd64
    failed. logfile at '../../releases/go-ipfs/v0.4.12/build-log-freebsd-amd64'
==> building for freebsd arm
    output to ../../releases/go-ipfs/v0.4.12/go-ipfs_v0.4.12_freebsd-arm
    failed. logfile at '../../releases/go-ipfs/v0.4.12/build-log-freebsd-arm'
==> building for linux 386
    output to ../../releases/go-ipfs/v0.4.12/go-ipfs_v0.4.12_linux-386
    failed. logfile at '../../releases/go-ipfs/v0.4.12/build-log-linux-386'
==> building for linux amd64
    output to ../../releases/go-ipfs/v0.4.12/go-ipfs_v0.4.12_linux-amd64
    failed. logfile at '../../releases/go-ipfs/v0.4.12/build-log-linux-amd64'
==> building for linux arm
    output to ../../releases/go-ipfs/v0.4.12/go-ipfs_v0.4.12_linux-arm
    failed. logfile at '../../releases/go-ipfs/v0.4.12/build-log-linux-arm'
==> building for windows 386
    output to ../../releases/go-ipfs/v0.4.12/go-ipfs_v0.4.12_windows-386
    failed. logfile at '../../releases/go-ipfs/v0.4.12/build-log-windows-386'
==> building for windows amd64
    output to ../../releases/go-ipfs/v0.4.12/go-ipfs_v0.4.12_windows-amd64
    failed. logfile at '../../releases/go-ipfs/v0.4.12/build-log-windows-amd64'

build complete!
```
[build-log-linux-amd64.txt](https://github.com/ipfs/distributions/files/1468418/build-log-linux-amd64.txt)

**Comment by kevina** [comment]
Note, now that dist.ipfs.io has v0.4.12 `make` no longer attempts to build it, is there a way to trick it to build it anyway?

**Comment by whyrusleeping** [comment]
@kevina thats a very strange issue. The log messages surrounding the 'commander' issue are all in a bash script. And the commander thing is a javascript issue...

**Comment by jessicaschilling** [comment]
Closing (stale), but please re-open if this continues to be an issue.
